#!/usr/bin/env python3
import argparse
from pathlib import Path

import matplotlib.pyplot as plt


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Plot serial bytes and highlight discontinuities between adjacent values."
    )
    parser.add_argument(
        "-i",
        "--input",
        # required=True,
        help="Input binary file generated by serial_reader.py",
    )
    parser.add_argument(
        "-o",
        "--output",
        default="data/serial_plot.png",
        help="Output image path, default: serial_plot.png",
    )
    parser.add_argument(
        "--wrap",
        action="store_true",
        help="Treat 255 -> 0 as continuous",
    )
    parser.add_argument(
        "--show",
        action="store_true",
        help="Display the plot window after saving",
    )
    return parser.parse_args()


def find_gaps(data: bytes, allow_wrap: bool) -> list[int]:
    gaps = []
    for idx in range(1, len(data)):
        expected = (data[idx - 1] + 1) & 0xFF if allow_wrap else data[idx - 1] + 1
        if data[idx] != expected and expected != 0x00:
            gaps.append(idx)
    return gaps


def main() -> int:
    args = parse_args()
    input_path = Path(args.input)
    output_path = Path(args.output)

    data = input_path.read_bytes()
    if not data:
        raise SystemExit(f"No data found in {input_path}")

    gaps = find_gaps(data, allow_wrap=args.wrap)
    x_values = list(range(len(data)))
    y_values = list(data)

    plt.figure(figsize=(14, 6))
    plt.plot(x_values, y_values, linewidth=0.8, color="#1f77b4", label="Byte value")

    if gaps:
        plt.scatter(
            gaps,
            [y_values[idx] for idx in gaps],
            color="#d62728",
            s=18,
            label=f"Discontinuities ({len(gaps)})",
            zorder=3,
        )

    plt.title("Serial Data Byte Plot")
    plt.xlabel("Byte Index")
    plt.ylabel("Byte Value")
    plt.ylim(-5, 260)
    plt.grid(True, linestyle="--", alpha=0.4)
    plt.legend()
    plt.tight_layout()

    output_path.parent.mkdir(parents=True, exist_ok=True)
    plt.savefig(output_path, dpi=150)

    print(f"Input file: {input_path.resolve()}")
    print(f"Total bytes: {len(data)}")
    print(f"Discontinuities: {len(gaps)}")
    if gaps:
        print("First discontinuity indexes:", gaps[:20])
    print(f"Plot saved to: {output_path.resolve()}")

    if args.show:
        plt.show()

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
